### ISSUE TITLE
TypeError: Cannot destructure property `compile` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by isathish** [mrgodhani/bookmark#1]
TypeError: Cannot destructure property `compile` of 'undefined' or 'null'.
    at addHooks (/Users/sathishkumarn/DEVELOPMENT/BookMarkes/bookmark-master/node_modules/webpack-dev-server/lib/Server.js:131:49)
    at new Server (/Users/sathishkumarn/DEVELOPMENT/BookMarkes/bookmark-master/node_modules/webpack-dev-server/lib/Server.js:144:5)
    at Promise (/Users/sathishkumarn/DEVELOPMENT/BookMarkes/bookmark-master/.electron-vue/dev-runner.js:62:20)
    at new Promise (<anonymous>)
    at startRenderer (/Users/sathishkumarn/DEVELOPMENT/BookMarkes/bookmark-master/.electron-vue/dev-runner.js:42:10)
    at init (/Users/sathishkumarn/DEVELOPMENT/BookMarkes/bookmark-master/.electron-vue/dev-runner.js:169:16)
    at Object.<anonymous> (/Users/sathishkumarn/DEVELOPMENT/BookMarkes/bookmark-master/.electron-vue/dev-runner.js:178:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
┏ Main Process ---------------

  Hash: 8947251b8d723898533d
  Version: webpack 2.7.0
  Time: 735ms
    Asset    Size  Chunks             Chunk Names
  main.js  190 kB       0  [emitted]  main
  
  WARNING in ./~/electron-debug/index.js
  81:45-58 Critical dependency: the request of a dependency is an expression
  
  WARNING in ./~/electron-debug/index.js
  84:85-106 Critical dependency: the request of a dependency is an expression

┗ ----------------------------

**Comment by isathish** [comment]
npm install -D webpack-dev-server@3.0.0
